import type { NextPage } from "next";
import Head from "next/head";

import { Box, Container, Text, Button, Flex, Image } from "@chakra-ui/react";
import { ContactForm } from "../modules/forms/ContactForm";

const Contact: NextPage = () => {
  return (
    <Box minHeight="100vh">
      <Head>
        <title>Contact - Distinguished Gentlemen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Text fontSize="4xl" fontWeight="medium">Contact Us!</Text>
        <Text>
          We&apos;d be happy to hear from you. Feel free to send a message via the
          Contact Form below and we&apos;ll get back to you as soon as we can!
        </Text>
        <ContactForm />
      </Container>
    </Box>
  );
};

export default Contact;
